### List all messages
GET http://localhost:3000/messages


### Create a new message
POST http://localhost:3000/messages
content-type: application/json

{
  "content": "added 1"
}

### Get a particular message
GET http://localhost:3000/messages/571

### Delete a particular message
Delete http://localhost:3000/messages/268

### update a particular message
PUT  http://localhost:3000/messages/571
content-type: application/json

{
  "content": "naya wala"
}